apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: airshield-gateway
  namespace: airshield
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: airshield-gateway
