"use client";

import { useEffect, useState } from "react";
import { Info, Play, ShieldCheck } from "lucide-react";
import { Button, Card, CardHeader, PageIntro, Pill } from "../ui";

const scenarios=[["Customer support call","8,400 labeled spans"],["Finance verification","4,210 labeled spans"],["Healthcare encounter","3,718 labeled spans"],["Noisy English audio","5,940 labeled spans"],["Adversarial leakage","1,260 canary probes"]];
export function PerformanceLab({notify}:{notify:(m:string)=>void}){
  const [selected,setSelected]=useState(scenarios[0][0]); const [progress,setProgress]=useState(0); const [running,setRunning]=useState(false); const done=progress===100;
  useEffect(()=>{if(!running)return;const id=setInterval(()=>setProgress(p=>{const next=Math.min(100,p+7);if(next===100)setRunning(false);return next}),140);return()=>clearInterval(id)},[running]);
  useEffect(()=>{if(done)notify("Synthetic English benchmark completed. Results are demo data.")},[done,notify]);
  return <div className="view"><PageIntro title="Measure before you claim" description="Benchmark detection recall, speaker separation, meaning preservation, leakage, and added latency on English test data." actions={<><Pill tone="amber">Synthetic demo corpus</Pill><Button variant="primary" onClick={()=>{setProgress(0);setRunning(true)}}><Play size={15}/>Run benchmark</Button></>}/><div className="lab-grid"><Card><CardHeader title="Test scenarios" subtitle="Choose a representative English workload"/><div className="scenario-list">{scenarios.map(s=><button key={s[0]} className={selected===s[0]?"active":""} onClick={()=>setSelected(s[0])}><i><ShieldCheck size={13}/></i><span><strong>{s[0]}</strong><small>{s[1]}</small></span></button>)}</div></Card><Card><CardHeader title="Evaluation run" subtitle={`${selected} · Self-hosted model stack`} action={<Pill tone={done?"green":running?"amber":"blue"}>{done?"Demo complete":running?"Running":"Ready"}</Pill>}/><div className="run-state"><span className="status-dot"/><span>{done?"Completed on synthetic corpus":running?"Evaluating local models…":"Waiting to run"}</span><strong>{progress}%</strong></div><div className="progress"><i style={{width:`${progress}%`}}/></div><div className="metric-grid">{[
        ["PII recall",done?"97.8%":"≥ 98%"],["Precision",done?"94.1%":"≥ 93%"],["Added p95",done?"74 ms":"< 150 ms"],["Critical leaks","0"],["Meaning retained",done?"96.4%":"≥ 95%"],["Realtime factor",done?"28×":"≥ 20×"]
      ].map(m=><div className={!done?"target":""} key={m[0]}><span>{m[0]}</span><strong>{m[1]}</strong><small>{done?"demo result":"pilot target"}</small></div>)}</div><div className="lab-note"><Info size={15}/><span>These values are simulated prototype data, not independent validation or a compliance guarantee. Production results require a labeled, representative corpus.</span></div><div className="entity-bars"><h3>Recall by entity class</h3>{[["Person names",98.2],["Account / record IDs",99.7],["Dates of birth",97.1],["Phone & email",99.4],["Addresses",94.8]].map(e=><div key={e[0]}><span>{e[0]}</span><i><b style={{width:done?`${e[1]}%`:"0%"}}/></i><strong>{done?`${e[1]}%`:"—"}</strong></div>)}</div></Card></div></div>
}
