apiVersion: v1
kind: Service
metadata: {name: airshield-postgresql, namespace: airshield}
spec:
  clusterIP: None
  selector: {app.kubernetes.io/name: airshield-postgresql}
  ports:
    - {name: postgres, port: 5432, targetPort: postgres}
