apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: airshield-key-vault
  namespace: airshield
spec:
  provider: azure
  secretObjects:
    - secretName: airshield-database
      type: Opaque
      data:
        - {objectName: database-url, key: url}
    - secretName: airshield-index-key
      type: Opaque
      data:
        - {objectName: token-index-key-b64, key: value}
  parameters:
    usePodIdentity: "false"
    clientID: REPLACE_MANAGED_IDENTITY_CLIENT_ID
    keyvaultName: REPLACE_KEY_VAULT_NAME
    tenantId: REPLACE_ENTRA_TENANT_ID
    objects: |
      array:
        - |
          objectName: database-url
          objectType: secret
          objectVersion: ""
        - |
          objectName: token-index-key-b64
          objectType: secret
          objectVersion: ""
